export const ALL_EMP_REQUEST = "ALL_EMP_REQUEST"
export const ALL_EMP_SUCCESS = "ALL_EMP_SUCCESS"
export const ALL_EMP_FAILURE = "ALL_EMP_FAILURE"

export const COV_POS_REQUEST = "COV_POS_REQUEST"
export const COV_POS_SUCCESS = "COV_POS_SUCCESS"
export const COV_POS_FAILURE = "COV_POS_FAILURE"

export const COV_NEG_REQUEST = "COV_NEG_REQUEST"
export const COV_NEG_SUCCESS = "COV_NEG_SUCCESS"
export const COV_NEG_FAILURE = "COV_NEG_FAILURE"